new_sylius_brand_admin_ajax:
    resource: "@NewSyliusBrandPlugin/config/routes/admin/ajax.yaml"
    prefix: /ajax

# new_sylius_brand_admin_brand:
#     resource: |
#         alias: new_sylius_brand.brand
#         section: admin
#         templates: "@SyliusAdmin\\Crud"
#         redirect: update
#         grid: new_sylius_brand_admin_brand
#         permission: true
#         vars:
#             all:
#                 subheader: new_sylius_brand.ui.brand
#                 templates:
#                     form: "@NewSyliusBrandPlugin/Admin/Brand/_form.html.twig"
#             index:
#                 icon: 'file image outline'
#     type: sylius.resource